services:
    App\Tests\Fixtures\Http\SearxFixtureHttpClient: ~

    App\Service\Searcher\SearcherFactory:
        arguments:
            $httpClient: '@App\Tests\Fixtures\Http\SearxFixtureHttpClient'

    App\Service\Reader\ReaderFactory:
        arguments:
            $httpClient: '@App\Tests\Fixtures\Http\SearxFixtureHttpClient'
